# version: '3.8'

# services:
#   web:
#     build: ./app
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./app/:/usr/src/app/
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env.dev

version: '3'

services:
  postgresdb:
    image: nomorefun/django:postgresdb
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
     - POSTGRES_PASSWORD=Userpass0
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  web:
    image: nomorefun/django:web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb
    ports:
      - '8000:8000'
    env_file:
      - .env.dev

